apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-message-hook-
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: post-message
        image: curlimages/curl:latest
        command:
          - /bin/sh
          - -c
          - |
            curl -X POST -H "Content-Type: application/json" \
            -d '{"message": "PreSync Application!"}' \
            https://webhook.site/129b18cf-1188-436c-8cc5-15459756e18e
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-message-hook-
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
      - name: post-message
        image: curlimages/curl:latest
        command:
          - /bin/sh
          - -c
          - |
            curl -X POST -H "Content-Type: application/json" \
            -d '{"message": "Sync Application!"}' \
            https://webhook.site/129b18cf-1188-436c-8cc5-15459756e18e
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-message-hook-
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: post-message
        image: curlimages/curl:latest
        command:
          - /bin/sh
          - -c
          - |
            curl -X POST -H "Content-Type: application/json" \
            -d '{"message": "PostSync Application!"}' \
            https://webhook.site/129b18cf-1188-436c-8cc5-15459756e18e
      restartPolicy: Never